export const _marketjson = [
  {
    id: 57,
    name: "KARNATAKA NIGHT",
    currentStatus: "CLOSED NOW",
    gameDisabled: "NO",
    saturdayOpen: "Open",
    sundayOpen: "Open",
    autoResult: "Off",
    openTime: "06:40 PM",
    closeTime: "07:40 PM",
    openResultTime: "06:45 PM",
    closeResultTime: "07:45 PM",
    createdAt: "2025-08-19 09:01:08",
  },
  {
    id: 56,
    name: "KARNATAKA DAY",
    currentStatus: "CLOSED NOW",
    gameDisabled: "NO",
    saturdayOpen: "Open",
    sundayOpen: "Open",
    autoResult: "Off",
    openTime: "10:10 AM",
    closeTime: "11:10 AM",
    openResultTime: "10:20 AM",
    closeResultTime: "11:20 AM",
    createdAt: "2025-08-19 08:54:47",
  },
  {
    id: 52,
    name: "MAIN BAZAR",
    currentStatus: "OPEN NOW",
    gameDisabled: "NO",
    saturdayOpen: "Close",
    sundayOpen: "Close",
    autoResult: "On",
    openTime: "09:50 PM",
    closeTime: "11:55 PM",
    openResultTime: "09:50 PM",
    closeResultTime: "11:55 PM",
    createdAt: "2023-06-21 11:12:13",
  },
  {
    id: 50,
    name: "RAJDHANI NIGHT",
    currentStatus: "OPEN NOW",
    gameDisabled: "NO",
    saturdayOpen: "Close",
    sundayOpen: "Close",
    autoResult: "Off",
    openTime: "09:30 PM",
    closeTime: "11:40 PM",
    openResultTime: "09:30 PM",
    closeResultTime: "11:40 PM",
    createdAt: "2023-06-17 06:20:00",
  },
  {
    id: 49,
    name: "KALYAN NIGHT",
    currentStatus: "OPEN NOW",
    gameDisabled: "NO",
    saturdayOpen: "Close",
    sundayOpen: "Close",
    autoResult: "Off",
    openTime: "09:20 PM",
    closeTime: "11:20 PM",
    openResultTime: "09:34 PM",
    closeResultTime: "11:30 PM",
    createdAt: "2023-06-17 06:18:23",
  },
  {
    id: 48,
    name: "MILAN NIGHT",
    currentStatus: "OPEN NOW",
    gameDisabled: "NO",
    saturdayOpen: "Open",
    sundayOpen: "Close",
    autoResult: "Off",
    openTime: "08:55 PM",
    closeTime: "10:55 PM",
    openResultTime: "09:05 PM",
    closeResultTime: "11:05 PM",
    createdAt: "2023-06-17 06:17:01",
  },
  {
    id: 47,
    name: "SUPREME NIGHT",
    currentStatus: "OPEN NOW",
    gameDisabled: "NO",
    saturdayOpen: "Open",
    sundayOpen: "Open",
    autoResult: "Off",
    openTime: "08:30 PM",
    closeTime: "10:30 PM",
    openResultTime: "08:45 PM",
    closeResultTime: "10:45 PM",
    createdAt: "2023-06-17 06:11:15",
  },
  {
    id: 46,
    name: "MADHUR NIGHT",
    currentStatus: "OPEN NOW",
    gameDisabled: "NO",
    saturdayOpen: "Open",
    sundayOpen: "Close",
    autoResult: "Off",
    openTime: "08:30 PM",
    closeTime: "10:30 PM",
    openResultTime: "08:30 PM",
    closeResultTime: "10:30 PM",
    createdAt: "2023-06-17 06:01:00",
  },
  {
    id: 45,
    name: "SRIDEVI NIGHT",
    currentStatus: "CLOSED NOW",
    gameDisabled: "NO",
    saturdayOpen: "Open",
    sundayOpen: "Open",
    autoResult: "Off",
    openTime: "07:00 PM",
    closeTime: "08:00 PM",
    openResultTime: "07:15 PM",
    closeResultTime: "08:15 PM",
    createdAt: "2023-06-17 05:58:48",
  },
  {
    id: 44,
    name: "KALYAN",
    currentStatus: "CLOSED NOW",
    gameDisabled: "NO",
    saturdayOpen: "Open",
    sundayOpen: "Close",
    autoResult: "Off",
    openTime: "03:30 PM",
    closeTime: "05:30 PM",
    openResultTime: "03:40 PM",
    closeResultTime: "05:40 PM",
    createdAt: "2023-06-17 05:55:49",
  },
];
